on:
  push:

env:
  DEPLOYER_VERSION: v7.3.0

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      APP_ENV: dev
      APP_DEBUG: 1
    steps:
      - uses: actions/checkout@v4

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get Yarn cache directory
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version-file: .php-version
          tools: composer:v2, composer-require-checker, symfony
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install PHP dependencies
        run: composer install -n --prefer-dist

      - name: Install and Build Yarn dependencies
        run: yarn install --no-progress --non-interactive && yarn build

      - name: Run Static test and Code validation
        run: |
          composer validate --no-check-publish
          composer-require-checker check
          symfony security:check --disable-exit-code
          vendor/bin/ecs check src
          vendor/bin/phpstan analyse -c phpstan.neon
          bin/console lint:twig templates/

  deploy:
    name: Build and Deploy to production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.ref_name == 'master'
    env:
      APP_ENV: prod
      APP_DEBUG: 0
    environment:
      name: production
      url: https://store.magentify.it
    steps:
      - uses: actions/checkout@v4

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get Yarn cache directory
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version-file: .php-version
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install PHP dependencies without developer dependencies
        run: composer install --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader --no-suggest --no-dev

      - name: Install and Build Yarn dependencies
        run: yarn install --no-progress --non-interactive && yarn build

      - name: Compress the artifact
        run: |
          rm -rf .git .github node_modules tests assets
          zip --symlinks -q -r deployer/build.zip . -x "deployer/*"

      - name: Create deployer-host.yml file
        run: echo '${{ secrets.DEPLOYER_HOST }}' >> deployer/host.yml

      - name: Deploy
        uses: deployphp/action@v1
        with:
          deployer-version: ${{ env.DEPLOYER_VERSION }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy
